---
title: get to class
name: get to class
author:
  name: Emil Sayahi
  "//facebook": your-id
  "//twitter": your-id
  github: FHEDUEmil
  "//linkedin": your-id
  "//medium": your-id
  "//tumblr": your-id
  email: emilsayahi@foresthills.edu
google-analytics:
  id: UA-85744932-1
disqus:
  id: gettoclass
url: https://fheduemil.github.io/
baseurl: ''
timezone: America/New_York
permalink: "/:year-:month-:day/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  imput: GFM
nav:
- name: About
  url: "/about"
- name: Archive
  url: "/archive"
- name: Tags
  url: "/tags"
- name: GitHub
  url: https://github.com/FHEDUEmil
  tag_page_layout: tag_page
tag_page_dir: tag
sass:
  sass_dir: _sass
  style: ":compressed"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
gems:
- jekyll-seo-tag
- jekyll-paginate
exclude:
- vendor
